name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Runs at 18:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    environment: secrets # Match the case of the environment name
    steps:
      - uses: actions/checkout@v3
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This will pull from the 'secrets' environment
          USERNAME: "CerealNotFound"
      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "generated"
          if [ -z "$(git status --porcelain)" ]; then
            echo "Nothing to commit"
          else
            git push
